version: '3.1'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_USER=boilerplate_go
      - POSTGRES_DB=boilerplate_go_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080